### ISSUE TITLE
hard links on sshfs

### ISSUE THREAD

**Issue by frankheckenbach** [miquels/liblockfile#9]
liblockfile does not seem to work on an sshfs mounted target. AFAICS, it gets confused since after link(2), sshfs reports the two links with different inode numbers which is a known limitation of sshfs.

When mounting the sshfs with "-o disable_hardlinks", link(2) fails right away which also doesn't help.

I realize this combination may simply not work, but I see your ChangeLog does mention sshfs, so is there some trick to get it to work?

**Comment by miquels** [comment]
I do not use sshfs. I searched back in the github issues, debian bug report, and mail, but I cannot find why the patch that the Changelog entry describes was added (other than that it really fixed an edge case). Any way, if a filesystem on a POSIX system is in fact not POSIX compatible, all bets are off. If some operations fail .. they fail.
